### ISSUE TITLE
Library does not support tensorflow-gpu

### ISSUE THREAD

**Issue by iTaybb** [aristofun/py-agender#1]
Hi,

the requirements.txt requires tensorflow specifically (which is the cpu version of tensorflow). In case where the gpu package is installed (tensorflow-gpu), the requirement won't be satisfied, and the cpu version will be installed instead.

This issue was also discussed on https://github.com/tensorflow/tensorflow/issues/7166

The fix would probably be to use "extras_require" or something.

Thanks
Itay

**Comment by aristofun** [comment]
Thank you. I currently have not enough time to research GPU compatibility, but would gladly accept PR if someone could do it.

**Comment by iTaybb** [comment]
I will do so when I got a moment.

**Comment by GregSkl** [comment]
Can you please release a new version now that py-agender supports GPU?

**Comment by aristofun** [comment]
Done https://pypi.org/project/py-agender/0.0.9/
